### ISSUE TITLE
Cannot download dataset using ecmwf-api source

### ISSUE THREAD

**Issue by jialinyi94** [ecmwf/earthkit-data#432] opened 2024-08-18 07:52 UTC
### What happened?

AttributeError: module 'earthkit.data.sources.ecmwf_api' has no attribute 'source'

### What are the steps to reproduce the bug?

```Python
import earthkit.data

ds = earthkit.data.from_source("ecmwf-api",
        param=["2t", "msl"],
        levtype="sfc",
        area=[50, -10, 40, 10], #N,W,S,E
        grid=[2, 2],
        date="2023-05-10"
)
```

### Version

0.9.3

### Platform (OS and architecture)

x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```shell
{
	"name": "AttributeError",
	"message": "module 'earthkit.data.sources.ecmwf_api' has no attribute 'source'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[30], line 1
----> 1 ds = earthkit.data.from_source(\"ecmwf-api\",
      2         param=[\"2t\", \"msl\"],
      3         levtype=\"sfc\",
      4         area=[50, -10, 40, 10], #N,W,S,E
      5         grid=[2, 2],
      6         date=\"2023-05-10\")

File ~/miniforge3/envs/alpha/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:150, in from_source(name, lazily, *args, **kwargs)
    147     return from_source_lazily(name, *args, **kwargs)
    149 prev = None
--> 150 src = get_source(name, *args, **kwargs)
    151 while src is not prev:
    152     prev = src

File ~/miniforge3/envs/alpha/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:128, in SourceMaker.__call__(self, name, *args, **kwargs)
    126     klass = self.SOURCES[name]
    127 else:
--> 128     klass = find_plugin(os.path.dirname(__file__), name, loader)
    129     self.SOURCES[name] = klass
    131 source = klass(*args, **kwargs)

File ~/miniforge3/envs/alpha/lib/python3.11/site-packages/earthkit/data/core/plugins.py:135, in find_plugin(directories, name, loader, refreshed)
    133                 candidates.add(p)
    134                 if p == name:
--> 135                     return loader.load_module(full.replace(\"/\", \".\"))
    137 if not refreshed:
    138     LOG.debug(\"Cannot find {loader.kind} 'name'. Refreshing plugin list.\")

File ~/miniforge3/envs/alpha/lib/python3.11/site-packages/earthkit/data/sources/__init__.py:107, in SourceLoader.load_module(self, module)
    106 def load_module(self, module):
--> 107     return import_module(module, package=__name__).source

AttributeError: module 'earthkit.data.sources.ecmwf_api' has no attribute 'source'"
}
```

**Comment by sandorkertesz** [comment] 2024-08-19 12:33
@jialinyi94, the problem is that "ecmwf-api" is not a valid "source". Please see the available sources here: https://earthkit-data.readthedocs.io/en/latest/guide/sources.html

**Comment by sandorkertesz** [comment] 2024-10-08 08:11
@jialinyi94, I presume it works for you now. Please can you confirm that I can close the issue?

**Comment by jialinyi94** [comment] 2024-10-11 08:19
Hi @sandorkertesz, yes the issue was fixed. Please feel free to close it.

**Closed** 2024-10-17 10:07 UTC
Labels: bug
